CREATE TABLE IF NOT EXISTS public.ITSupport (
    Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Region text NOT NULL CHECK (Region IN ('VMB', 'VMT', 'VMN')),
    DisplayName text NOT NULL,
    Username text,
    Email text,
    TeamsUrl text,
    Phone text,
    IsActive boolean NOT NULL DEFAULT TRUE,
    SortOrder integer NOT NULL DEFAULT 0,
    CreatedAt timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_itsupport_active_sort
    ON public.ITSupport (IsActive, SortOrder, Region, Id);

DO $seed$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.AppSettings WHERE Key = 'ItSupportSeedV1') THEN
        INSERT INTO public.ITSupport
            (Region, DisplayName, Username, Email, TeamsUrl, IsActive, SortOrder)
        VALUES
            ('VMB', 'CONGNT01', 'CONGNT01', 'congnt01@sungroup.com.vn', NULL, TRUE, 1),
            ('VMT', 'DUCDM', 'DUCDM', 'ducdm@sungroup.com.vn', NULL, TRUE, 2),
            ('VMN', 'TUHN01', 'TUHN01', 'tuhn01@sungroup.com.vn', NULL, TRUE, 3);

        INSERT INTO public.AppSettings (Key, Value)
        VALUES ('ItSupportSeedV1', 'complete')
        ON CONFLICT (Key) DO NOTHING;
    END IF;
END
$seed$;