-- SGR NetGuard PostgreSQL bootstrap. Run with psql against the target database.
CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.Sites (
    Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Region text NOT NULL, SiteName text NOT NULL,
    Subnet text NOT NULL, ItAccount text NOT NULL, TeamsAccount text NOT NULL, IsActive boolean NOT NULL DEFAULT true,
    UpdatedAtUtc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, UpdatedBy text
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_sites_region_name ON public.Sites (Region, SiteName);
CREATE TABLE IF NOT EXISTS public.RegionDnsServers (Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Region text NOT NULL, DnsServer text NOT NULL, UNIQUE (Region, DnsServer));
CREATE TABLE IF NOT EXISTS public.AppSettings (Key text PRIMARY KEY, Value text NOT NULL);
CREATE TABLE IF NOT EXISTS public.PerformanceWarnings (Id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, DeviceName text NOT NULL, SiteName text, Region text, MetricType text NOT NULL, MetricValue numeric(5,2) NOT NULL, WarnedAtUtc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS public.DeviceHeartbeats (
    DeviceName text PRIMARY KEY, LastSiteName text, LastRegion text, LastInternalSeenUtc timestamptz, IsInternal boolean NOT NULL DEFAULT false,
    AppVersion text, LastSeenUtc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, CpuPercent numeric(5,2), RamPercent numeric(5,2), DiskPercent numeric(5,2), NetworkLatencyMs integer,
    AdJoined boolean, TrellixInstalled boolean, DesktopCentralInstalled boolean, LoggedInUser text, LanIp text, PublicIp text, MacAddress text, Domain text, WindowsVersion text,
    SerialNumber text, CpuModel text, RamTotal text, DiskTotal text, Mainboard text, Uptime text, DetailUpdatedUtc timestamptz, NetworkType text, WifiSignalDbm integer, LanLinkSpeed text
);
CREATE TABLE IF NOT EXISTS public.Devices (
    Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, DeviceId uuid NOT NULL UNIQUE, MACAddress text, ComputerName text, CurrentUser text, CurrentDepartment text, CurrentLocation text, OperatingSystem text,
    FirstSeen timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, LastSeen timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, Status text NOT NULL DEFAULT 'Active', NetworkWarningDisabled boolean NOT NULL DEFAULT false, NetworkWarningDisabledAt timestamptz
);
CREATE TABLE IF NOT EXISTS public.DeviceHistory (Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, DeviceId uuid NOT NULL, MACAddress text, ComputerName text, Username text, Department text, Location text, Timestamp timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, ChangeType text NOT NULL DEFAULT 'DEVICE_INFO_CHANGED');
CREATE TABLE IF NOT EXISTS public.NetworkStatus (Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, DeviceId uuid NOT NULL, ConnectionType text, AdapterName text, IPAddress text, MACAddress text, SSID text, SignalStrengthDbm numeric(6,2), LinkSpeedMbps numeric(10,2), DownloadMbps numeric(10,2), UploadMbps numeric(10,2), Timestamp timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS public.PerformanceLogs (Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, DeviceId uuid NOT NULL, CPUUsage numeric(6,2), RAMUsage numeric(6,2), DiskUsage numeric(6,2), DiskRead numeric(10,2), DiskWrite numeric(10,2), DiskIO numeric(10,2), TopProcess text, Timestamp timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS public.ComplianceStatus (Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, DeviceId uuid NOT NULL, Antivirus text, Firewall text, WindowsUpdate text, BitLocker text, PasswordPolicy text, EndpointProtection text, OverallStatus text NOT NULL DEFAULT 'Unknown', Timestamp timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS public.SoftwareInventory (Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, DeviceId uuid NOT NULL, SoftwareName text NOT NULL, Version text, Publisher text, InstallDate timestamptz, FirstDetected timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, LastDetected timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE (DeviceId, SoftwareName));
CREATE TABLE IF NOT EXISTS public.Alerts (Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, DeviceId uuid, AlertType text NOT NULL, Severity text NOT NULL DEFAULT 'Warning', Title text NOT NULL, Message text, IsAcknowledged boolean NOT NULL DEFAULT false, CreatedAt timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, ResolvedAt timestamptz);
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS LastInternalSeenUtc timestamptz;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS CpuPercent numeric(5,2);
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS RamPercent numeric(5,2);
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS DiskPercent numeric(5,2);
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS NetworkLatencyMs integer;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS AdJoined boolean;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS TrellixInstalled boolean;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS DesktopCentralInstalled boolean;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS LoggedInUser text;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS LanIp text;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS PublicIp text;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS MacAddress text;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS Domain text;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS WindowsVersion text;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS SerialNumber text;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS CpuModel text;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS RamTotal text;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS DiskTotal text;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS Mainboard text;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS Uptime text;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS DetailUpdatedUtc timestamptz;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS NetworkType text;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS WifiSignalDbm integer;
ALTER TABLE public.DeviceHeartbeats ADD COLUMN IF NOT EXISTS LanLinkSpeed text;
CREATE INDEX IF NOT EXISTS ix_performancewarnings_device_time ON public.PerformanceWarnings(DeviceName, WarnedAtUtc);
CREATE INDEX IF NOT EXISTS ix_devicehistory_device_time ON public.DeviceHistory(DeviceId, Timestamp);
CREATE INDEX IF NOT EXISTS ix_networkstatus_device_time ON public.NetworkStatus(DeviceId, Timestamp);
CREATE INDEX IF NOT EXISTS ix_performancelogs_device_time ON public.PerformanceLogs(DeviceId, Timestamp);
CREATE INDEX IF NOT EXISTS ix_compliancestatus_device_time ON public.ComplianceStatus(DeviceId, Timestamp);
INSERT INTO public.AppSettings(Key, Value) VALUES ('ValidSsid', 'SGR-OFFICE') ON CONFLICT (Key) DO NOTHING;
CREATE OR REPLACE VIEW public.vw_WeeklyPerformanceReport AS
SELECT DeviceName, SiteName, Region, COUNT(*) FILTER (WHERE MetricType = 'CPU') AS CpuWarningCount, COUNT(*) FILTER (WHERE MetricType = 'RAM') AS RamWarningCount, COUNT(*) FILTER (WHERE MetricType = 'Disk') AS DiskWarningCount, COUNT(*) AS TotalWarningCount, MAX(WarnedAtUtc) AS LastWarningUtc
FROM public.PerformanceWarnings WHERE WarnedAtUtc >= CURRENT_TIMESTAMP - INTERVAL '7 days' GROUP BY DeviceName, SiteName, Region;